database: 
  db-name: "alan"

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/${database.db-name}"
    username: "postgres"
    password: "admin1234"

  thymeleaf:
    cache: false 
    prefix: classpath:/templates/
    encoding: UTF-8 
    suffix: .html 
    mode: HTML 



spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update
  # Hibernate ddl auto (create, create-drop, validate, update)
